#!/bin/sh

arg1=$1

##directory where jar file is located    
dir=out/artifacts/Go_jek_main_jar

##jar file name
jar_name=Go_jek.main.jar

gradle clean build

## Permform some validation on input arguments, one example below
if [ -z "$1" ] ; then
        java -jar $dir/$jar_name
        exit 1

else
	java -jar $dir/$jar_name $arg1

fi
